name: Test

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test-default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-13
          - macos-14
          - macos-15
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-25.04
          - windows-2019
          - windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run all
      - uses: ./
      - run: the -v
  test-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-13
          - macos-14
          - macos-15
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-25.04
          - windows-2019
          - windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run all
      - uses: ./
        with:
          the-version: 0.14.0
      - run: the -v
  test-version-before-macos-arch-change:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run all
      - uses: ./
        with:
          the-version: 0.13.0
      - run: the -v
